#
# Makefile
#
# Computer Science 50
# Problem Set 3
#
# clang -ggdb3 -O0 -std=c99 -Wall -Werror -o fifteen fifteen.c -lcs50 -lm

fifteen: fifteen.c
	gcc -I ~/cs50-fall2013/cs50lib -ggdb -O0 -std=c99 -Wall -Werror -o fifteen fifteen.c ~/cs50-fall2013/cs50lib/cs50.c

clean:
	rm -f *.o a.out core fifteen